---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1671393/public_html/thoyiburrohman.my.id
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp -r resources $DEPLOYPATH
    - /bin/cp -r routes $DEPLOYPATH
